### ISSUE TITLE
Stopping roscore 

### ISSUE THREAD

**Issue by JonasFrey96** [ori-drs/procman_ros#36]
Hello,

firstly, thanks for this cool tool !
When using `--start-roscore` is there a way to automatically stop the roscore when closing procman.
My current solution of calling `killall -9 roscore` is not so nice.

Best Jonas

**Comment by heuristicus** [comment]
Hi Jonas,

Glad you're finding the tool useful. I've noted this in #30 but haven't had time to fix it since we don't use this option much. If you close the window with alt-f4 or using the usual close window button the roscore will persist currently. If you close it with ctrl-c on the commandline the roscore will exit.

I will have a look at fixing this soon.

**Comment by heuristicus** [comment]
I've pushed a change which should fix this.
